/** Catálogo real da Primu's Bolos (extraído dos prints). Preço em centavos. */
export const CATALOG = [
  {
    name: "Bolo de Cenoura com Chocolate",
    slug: "cenoura-chocolate",
    description: "Massa fofinha de cenoura com casquinha generosa de chocolate e granulado.",
    price: 1800,
    imageUrl: "/bolos/cenoura-chocolate.webp",
    sortOrder: 1,
  },
  {
    name: "Bolo de Milho Verde com Fubá",
    slug: "milho-verde-fuba",
    description: "Sabor caseiro de milho verde com fubá — úmido e na medida do doce.",
    price: 1600,
    imageUrl: "/bolos/milho-verde-fuba.webp",
    sortOrder: 2,
  },
  {
    name: "Bolo de Banana com Canela",
    slug: "banana-canela",
    description: "Banana caramelizada com um toque de canela. Cheiro de fim de tarde.",
    price: 1600,
    imageUrl: "/bolos/banana-canela.webp",
    sortOrder: 3,
  },
  {
    name: "Bolo Fazendeiro",
    slug: "fazendeiro",
    description: "Bolo rústico coberto de coco branquinho, do jeito da roça.",
    price: 1600,
    imageUrl: "/bolos/fazendeiro.webp",
    sortOrder: 4,
  },
  {
    name: "Bolo de Goiabada com Queijo",
    slug: "goiabada-queijo",
    description: "O clássico Romeu e Julieta: goiabada cremosa com queijo.",
    price: 1600,
    imageUrl: "/bolos/goiabada-queijo.webp",
    sortOrder: 5,
  },
  {
    name: "Bolo de Limão",
    slug: "limao",
    description: "Massa molhadinha com cobertura cremosa de limão e raspas fresquinhas.",
    price: 1800,
    imageUrl: "/bolos/limao.webp",
    sortOrder: 6,
  },
  {
    name: "Bolo de Massa Puba",
    slug: "massa-puba",
    description: "Receita tradicional de massa puba, macia e cheia de memória afetiva.",
    price: 1600,
    imageUrl: "/bolos/massa-puba.webp",
    sortOrder: 7,
  },
  {
    name: "Bolo Negresco",
    slug: "negresco",
    description: "Recheado e coberto com pedaços de biscoito Negresco. Irresistível.",
    price: 1600,
    imageUrl: "/bolos/negresco.webp",
    sortOrder: 8,
  },
  {
    name: "Bolo de Ninho",
    slug: "ninho",
    description: "Massa delicada com cobertura cremosa de leite Ninho.",
    price: 2000,
    imageUrl: "/bolos/ninho.webp",
    sortOrder: 9,
  },
  {
    name: "Bolo Pudim",
    slug: "pudim",
    description: "Dois em um: pudim cremoso por cima e bolo fofinho por baixo, com calda de caramelo.",
    price: 2000,
    imageUrl: "/bolos/pudim.webp",
    sortOrder: 10,
  },
  {
    name: "Rocambole de Chocolate",
    slug: "rocambole-chocolate",
    description: "Rolinho de chocolate recheado, coberto com granulado e morango.",
    price: 2000,
    imageUrl: "/bolos/rocambole-chocolate.webp",
    sortOrder: 11,
  },
  {
    name: "Bolo Vulcão",
    slug: "vulcao",
    description: "Bolo de chocolate com casquinha crocante, crocantes ao leite e morango no topo.",
    price: 2000,
    imageUrl: "/bolos/vulcao.webp",
    sortOrder: 12,
  },
];
